# This is a basic workflow to help you get started with Actions

name: Build and Deploy React to Firebase

on:
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - run: npm install
            - run: npm run-script build
            - uses: actions/upload-artifact@master
              with:
                  name: build
                  path: build
    deploy:
        name: Deploy to firebase
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@master
              with:
                  name: build
                  path: build
            - run: ls
            - name: Deploying...
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
                  PROJECT_PATH : ./react-expense-tracker
